services:
  postgres:
    image: postgres:16
    container_name: sysadmin-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monitordb
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: